name: smart_hospital
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  dotted_border: ^2.0.0+2
  shared_preferences: ^2.0.15
  logger: ^1.1.0
  equatable: ^2.0.5
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  bot_toast: ^4.0.3
  transparent_image: ^2.0.0
  intl: ^0.17.0
  local_auth: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  geolocator: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  assets:
    - lib/src/assets/images/

